In [11]:
class SLR:
    def __init__(self):
        self.m=None
        self.b=None

    def fit(self,X_train,y_train):
        X_train=X_train.values
        y_train=y_train.values
        num= sum((X_train-X_train.mean())*(y_train-y_train.mean()))
        den= sum((X_train-X_train.mean())*(X_train-X_train.mean()))
        self.m=num/den
        self.b= (y_train.mean())-(self.m*X_train.mean())

    def predict(self,X_test):
        X_test=X_test.values
        print(X_test.ndim)
        return ((self.m*X_test)+self.b)


In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df=pd.read_csv('placement.csv')
X=df.iloc[:,0]
y=df.iloc[:,-1]

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [14]:
model=SLR()

In [15]:
X_train.info()

<class 'pandas.Series'>
Index: 160 entries, 137 to 168
Series name: cgpa
Non-Null Count  Dtype  
--------------  -----  
160 non-null    float64
dtypes: float64(1)
memory usage: 2.5 KB


In [16]:
model.fit(X_train,y_train)

In [17]:
X_test.ndim

1

In [18]:
model.predict(X_test)

1


array([3.89111601, 3.09324469, 2.38464568, 2.57434935, 1.6537286 ,
       1.77647803, 2.07219258, 2.93143862, 3.76278706, 2.93701814,
       4.09197872, 3.51170867, 2.97049525, 2.40138424, 3.18809652,
       3.46707251, 1.94386362, 3.24389172, 2.97607477, 3.41685683,
       2.55761079, 3.16577844, 2.85890486, 3.12114229, 3.68467378,
       2.8700639 , 3.49497011, 3.34432308, 3.91901361, 1.96060218,
       3.65119666, 3.2104146 , 3.74046898, 2.7863711 , 2.78079158,
       3.27178932, 3.52844723, 2.61340599, 2.65804215, 2.71383735])

In [19]:
y_test.values

array([4.1 , 3.49, 2.08, 2.33, 1.94, 1.48, 1.86, 3.09, 4.21, 2.87, 3.65,
       4.  , 2.89, 2.6 , 2.99, 3.25, 1.86, 3.67, 2.37, 3.42, 2.48, 3.65,
       2.6 , 2.83, 4.08, 2.56, 3.58, 3.81, 4.09, 2.01, 3.63, 2.92, 3.51,
       1.94, 2.21, 3.34, 3.34, 3.23, 2.01, 2.61])

In [20]:
model.predict(pd.Series([8.35]))

1


array([3.76278706])